package org.usfirst.frc.team3546.robot.subsystems;

import edu.wpi.cscore.UsbCamera;
import edu.wpi.first.wpilibj.CameraServer;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 * Created by User on 1/18/2017.
 */
public class Camera extends Subsystem {

    public Camera() {
        try {
           UsbCamera Camera = CameraServer.getInstance().startAutomaticCapture();
           Camera.setResolution(160, 120);
           Camera.setFPS(30);

            //cameraServer.setQuality(50);
        } catch (Exception e) {
            //DriverStation.reportError("Camera 'cam0' not found. Is it plugged in?", false);
        }
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


        // Put methods for controlling this subsystem
        // here. Call these from Commands.
    }

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
}
